services:
  - type: web
    name: ol-kalou-frontend
    env: static
    buildCommand: npm install && npm run build
    staticPublishPath: ./dist
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
    envVars:
      - key: VITE_API_URL
        value: https://exs-d8vf7tflk1mc738t0s40.onrender.com/api
